gbuttons = [
    ['<b>Ж</b>','<b>%s</b>'],
    ['<i>К</i>', '<i>%s</i>'],
    ['<span style="display: inline-block;margin-top: -5px;">x<sup>2</sup></span>', "<sup>%s</sup>"],
    ['x<sub>2</sub>', '<sub>%s</sub>'],
    ['«»', '«%s»'],
    ['+','&#8239;+&#8239;'],
    ['<span title="Минус, использовать с прописными буквами и цифрами, пример: 1 − 2, M − N">−</span>', '−'],
    ['<span title="Среднее тире, использовать со строчными буквами и их комбинацией с другими, пример: 2 – a, a – b, –&pi;. Нужно оборачивать в nobr">–</span>', '–'],
    ['=','&#8239;&#8239;=&#8239;&#8239;'],
    ['·','&#8239;·&#8239;'],
    ['°','°'],
    ['nobr','<nobr>%s</nobr>'],
    ['&#8239;', '&#8239;'],
    ['<span title="Длинное тире, пример использования: корова — это животное">—</span>', '—'],
    ['<img src="/img/align_center.png" style="vertical-align:-4px">','##<center>\n%s\n##</center>'],
    ['<img alt="" src="/img/two_col.png" title="Заготовка для отображения двух адаптивных колонок">','<div class="wrap_flex_table">\n<div class="wrap_flex_table_col">\n<div class="col_name">НАЗВАНИЕ 1</div>\n<div class="col_content">\nA) Пункт\nБ) Пункт\nВ) Пункт\n</div>\n</div>\n<div class="wrap_flex_table_col">\n<div class="col_name"> НАЗВАНИЕ 2</div>\n<div class="col_content">\n1) Пункт\n2) Пункт\n</div>\n</div>\n</div>'],
    ['<img src="/img/mq_left_center.svg" style="margin-top: 1px;" title="Колонка с ровным левым краем, размещена по центру. Можно задать ширину (width), заменить center на left, чтобы установить единый отступ для нескольких колонок в тексте">','<div class="wrap_flex_center" style="width:auto;"><div class="col_content">\n%s\n</div></div>'],
    ['<span title="Заготовка для отображения нескольких картинок по центру с подписями">К_К</span>','<div class="flex-img">\n<div>\n<img src="/get_file?id=90049" style="margin:10px auto;display:block;max-width:none">\n<nobr>1. Слева-направо </nobr>\n</div>\n<div>\n<img src="/get_file?id=90049" style="margin:10px auto;display:block;max-width:none">\n<nobr>Разность этих скоростей </nobr>\n</div>\n<div>\n<img src="/get_file?id=90049" style="margin:10px auto;display:block;max-width:none">\n<nobr>И тогда ответ в этом случае </nobr>\n</div>\n</div>'],
    ['<span title="">Т_Т</span>','<div class="flex-wrapper-items">\n%s\n</div>'],
    [2],
    ['О', '<span style="letter-spacing: 2px;">Ответ:</span> '],
    ['П', '<span style="letter-spacing: 2px;">Правильный ответ указан под номером</span> '],
    ['<span title="Вставка поля ответа в произвольное место задания">Поле</span>', '<input class="test_inp" name="answer_part_1" size=5>'],
    ['У', '<!--include ege.rus.12345.body-->'],
    ['Р', '<!--include ege.rus.12345.solution-->'],
    ['К', '<!--include ege.rus.12345.answer_1-->'],
    [6],
    [],
    ['<span style="letter-spacing: -1px;">___</span>', '<span class="rus_single">%s</span>'],
    ['<span style="display: inline-block;letter-spacing: -4px;padding-top: 5px;width: 21px;">===</span>', '<span class="rus_double">%s</span>'],
    ['<span style="display: inline-block;padding-top: 4px;">~~~</span>', '<span class="rus_wave">%s</span>'],
    ['<span style="display: inline-block;padding-top: 4px;">- - -</span>', '<span class="rus_dashed">%s</span>'],
    ['<span style="display: inline-block;padding-top: 4px;">&ndash;·&ndash;</span>', '<span class="rus_dotteddash">%s</span>'],
    ['x2', '<span style="font-size:1.5em">%s</span>'],
    ['a&#769;', '%s&#769;'],
    ['пр.', '<span class="prefix">%s</span>'],
    ['кор.', '<span class="root">%s</span>'],
    ['суфф.', '<span class="suffix">%s</span>'],
    ['ок.', '<span class="ending">%s</span>'],
    ['осн.', '<span class="base">%s</span>'],
    ['сущ.', '<span class="sup_cont"><span class="sup_word">сущ.</span>%s</span>'],
    ['глаг.', '<span class="sup_cont"><span class="sup_word">глаг.</span>%s</span>'],
    ['нар.', '<span class="sup_cont"><span class="sup_word">нар.</span>%s</span>'],
    ['прил.', '<span class="sup_cont"><span class="sup_word">прил.</span>%s</span>'],
    ['мест.', '<span class="sup_cont"><span class="sup_word">мест.</span>%s</span>'],
    ['предл.', '<span class="sup_cont"><span class="sup_word">предл.</span>%s</span>']
];

